name: CSBC bot news poster
run-name: ${{ github.actor }} start deployment 🚀
on:
    push:
        branches:
            - master
            - develop
    pull_request:
        branches:
            - master
            - develop
jobs:
    
